AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sam-app
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  SNSTopicArn:
    Type: String
    Description: The ARN of the SNS topic for the environment.

  LambdaExecutionRoleArn:
    Type: String
    Description: The ARN of the IAM role that the Lambda function will assume.
  AuthId:
    Type: String
    Description: The ID of the authentication secret.  

Resources:
  RootCertsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Layer to store root certificates for RESTful API access/scritp tneed to download root certs
      ContentUri: ./certs-layer
      CompatibleRuntimes:
        - nodejs20.x

  SNSPayloadLogger:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that logs the payload of messages sent to an
        associated SNS topic.
      Runtime: nodejs20.x
      Handler: handlers/app.handler
      CodeUri: ./dist
      Role: !Ref LambdaExecutionRoleArn  # Pass the role ARN here
      Layers:
        - !Ref RootCertsLayer
      Environment:
        Variables:
          AUTH_SECRET: "inject-here-s"
          AUTH_ID: !Ref AuthId
      Events:
        SNSTopicEvent:
          Type: SNS
          Properties:
            Topic: !Ref SNSTopicArn
      MemorySize: 128
      Timeout: 100
      Policies:
        - AWSLambdaBasicExecutionRole
    Metadata:
      SamResourceId: SNSPayloadLogger
      TestEvent:
        SNSPayloadEvent:
          TopicArn: "arn:aws:sns:us-west-2:123456789012:SimpleTopic"
          Message: "This is a notification from SNS"
          Subject: "SNS Notification"
